[{"id":1,"name":"sec1","tags":"Section 1","templateId":1,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":null,
  "subSections":[{"id":2,"name":"sec2","tags":"Section 2","templateId":1,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":1,
                    "subSections":[{"id":3,"name":"sec3","tags":"Section 3","templateId":2,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":2,
                                  "subSections":[],
                                  "uiComponents":[]}],
                    "uiComponents":[{"id":2,"title":"uiComp2","type":"uiComponent","tags":"uiComponent","properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","sectionId":2}]},
                 {"id":4,"name":"sec4","tags":"Section 4","templateId":1,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":1,
                 "subSections":[],
                 "uiComponents":[]}],
  "uiComponents":[{"id":1,"title":"uiComp1","type":"uiComponent","tags":"uiComponent","properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","sectionId":1},{"id":3,"title":"uiComp3","type":"uiComponent","tags":"uiComponent","properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","sectionId":1},{"id":4,"title":"uiComp4","type":"uiComponent","tags":"uiComponent","properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","sectionId":1}]},
{"id":2,"name":"sec2","tags":"Section 2","templateId":1,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":1,
"subSections":[{"id":3,"name":"sec3","tags":"Section 3","templateId":2,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":2,"subSections":[],"uiComponents":[]}],"uiComponents":[{"id":2,"title":"uiComp2","type":"uiComponent","tags":"uiComponent","properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","sectionId":2}]},{"id":4,"name":"sec4","tags":"Section 4","templateId":1,"properties":"{\r\n\"Property1\": \"XYZ\"\r\n}","parentSectionId":1,
"subSections":[],
"uiComponents":[]}]
